service {
  name = "QUIZ"
  name = ${?QUIZ_SERVICE_NAME}

  host = "0.0.0.0"
  host = ${?QUIZ_SERVER_HOST}

  port = 2222
  port = ${?QUIZ_SERVER_PORT}

  idle-timeout-minutes = 30
  idle-timeout-minutes = ${?QUIZ_SERVER_IDLE_TIMEOUT_MINUTES}
}

cors {
  any-origin = true
  any-origin = ${?QUIZ_CORS_ANY_ORIGIN}

  allow-credentials = true
  allow-credentials = ${?QUIZ_CORS_ALLOW_CREDENTIALS}

  max-age-seconds = 86400
  max-age-seconds = ${?QUIZ_CORS_MAX_AGE_SECONDS}

  any-method = true
  any-method = ${?QUIZ_CORS_ANY_METHOD}
}

data {
  mode-file = "modes.json"
  mode-file = ${?QUIZ_MODE_FILE}
}

word-service {
  host = "localhost"
  host = ${?WORD_SERVICE_HOST}

  port = 1111
  port = ${?WORD_SERVICE_PORT}

  base-url = "http://localhost:1111"
  base-url = ${?QUIZ_WORD_SERVICE_URL}

  request-timeout-seconds = 1.0
  request-timeout-seconds = ${?QUIZ_WORD_SERVICE_TIMEOUT_SECONDS}
}

quiz {
  default-size = 10
  default-size = ${?QUIZ_DEFAULT_SIZE}
}
