service {
  name = "WORD"
  name = ${?WORD_SERVICE_NAME}

  host = "0.0.0.0"
  host = ${?WORD_SERVER_HOST}

  port = 1111
  port = ${?WORD_SERVER_PORT}

  idle-timeout-minutes = 30
  idle-timeout-minutes = ${?WORD_SERVER_IDLE_TIMEOUT_MINUTES}
}

cors {
  any-origin = true
  any-origin = ${?WORD_CORS_ANY_ORIGIN}

  allow-credentials = true
  allow-credentials = ${?WORD_CORS_ALLOW_CREDENTIALS}

  max-age-seconds = 86400
  max-age-seconds = ${?WORD_CORS_MAX_AGE_SECONDS}

  any-method = true
  any-method = ${?WORD_CORS_ANY_METHOD}
}

data {
  dictionary-extension = "JSON"
  dictionary-extension = ${?WORD_DICTIONARY_EXTENSION}

  dir = ""
  dir = ${?WORD_DATA_DIR}

  seed-dir = ""
  seed-dir = ${?WORD_SEED_DIR}
}
