name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  #--------------------------------------------- FRONTEND
  test-frontend-html-changes:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: test html frontend changes
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: checking changed files in frontend
        id: changed-frontend
        uses: tj-actions/changed-files@v37
        with:
          files: frontend/**
      - name: log frontend files NOT changed
        if: steps.changed-frontend.outputs.any_changed != 'true'
        run: echo frontend files not changed
      - name: run html frontent checks
        if: steps.changed-frontend.outputs.any_changed == 'true'
        uses: anishathalye/proof-html@v2.0.4
        with:
          directory: frontend/
  #--------------------------------------------- BACKEND: QUIZ SERVICE
  test-backend-quiz-changes:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: test quiz backend changes
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: checking changed files in backend quiz service
        id: changed-quiz-backend
        uses: tj-actions/changed-files@v37
        with:
          files: backend/service-quiz/**
      - name: backend quiz files NOT changed
        if: steps.changed-quiz-backend.outputs.any_changed != 'true'
        run: echo backend quiz service NOT changed
      - name: compike quiz backend service
        if: steps.changed-quiz-backend.outputs.any_changed == 'true'
        working-directory: backend/service-quiz
        run: sbt clean compile
      - name: run quiz backend service unit tests
        if: steps.changed-quiz-backend.outputs.any_changed == 'true'
        working-directory: backend/service-quiz
        run: sbt coverage test
      - name: generate quiz backend service coverage report
        if: steps.changed-quiz-backend.outputs.any_changed == 'true'
        working-directory: backend/service-quiz
        run: sbt coverageReport
  #--------------------------------------------- BACKEND: WORD SERVICE
  test-backend-word-changes:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: test word backend changes
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: checking changed files in backend word service
        id: changed-word-backend
        uses: tj-actions/changed-files@v37
        with:
          files: backend/service-word/**
      - name: backend word files NOT changed
        if: steps.changed-word-backend.outputs.any_changed != 'true'
        run: echo backend word service NOT changed
      - name: compile word backend service
        if: steps.changed-word-backend.outputs.any_changed == 'true'
        working-directory: backend/service-word
        run: sbt clean compile
      - name: run word backend service unit tests
        if: steps.changed-word-backend.outputs.any_changed == 'true'
        working-directory: backend/service-word
        run: sbt coverage test
      - name: generate word backend service coverage report
        if: steps.changed-word-backend.outputs.any_changed == 'true'
        working-directory: backend/service-word
        run: sbt coverageReport
