name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  #--------------------------------------------- FRONTEND
  test-frontend-html-changes:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: test html frontend changes
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: checking changed files in frontend
        id: changed-frontend
        uses: tj-actions/changed-files@v37
        with:
          files: frontend/**
      - name: log frontend files NOT changed
        if: steps.changed-frontend.outputs.any_changed != 'true'
        run: echo frontend files not changed
      - name: run html frontent checks
        if: steps.changed-frontend.outputs.any_changed == 'true'
        uses: anishathalye/proof-html@v2.0.4
        with:
          directory: frontend/
  #--------------------------------------------- BACKEND: QUIZ SERVICE
  check-backend-quiz-changes:
    runs-on: ubuntu-latest
    name: check quiz backend changes
    outputs:
      changes_present: ${{ steps.changed-quiz-backend.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: checking changed files in backend quiz service
        id: changed-quiz-backend
        uses: tj-actions/changed-files@v37
        with:
          files: backend/service-quiz/**
      - name: log backend quiz WAS changed
        if: steps.changed-quiz-backend.outputs.any_changed == 'true'
        run: echo backend quiz service WAS changed
      - name: log backend quiz NOT changed
        if: steps.changed-quiz-backend.outputs.any_changed != 'true'
        run: echo backend quiz service NOT changed
  test-backend-quiz-changes:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: test quiz backend changes
    needs: [check-backend-quiz-changes]
    if: needs.check-backend-quiz-changes.outputs.changes_present == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: run quiz backend service unit tests
        working-directory: backend/service-quiz
        run: sbt coverage test
      - name: generate quiz backend service coverage report
        working-directory: backend/service-quiz
        run: sbt coverageReport
  #--------------------------------------------- BACKEND: WORD SERVICE
  check-backend-word-changes:
    runs-on: ubuntu-latest
    name: check word backend changes
    outputs:
      changes_present: ${{ steps.changed-word-backend.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: checking changed files in backend word service
        id: changed-word-backend
        uses: tj-actions/changed-files@v37
        with:
          files: backend/service-word/**
      - name: log backend word WAS changed
        if: steps.changed-word-backend.outputs.any_changed == 'true'
        run: echo backend word service WAS changed
      - name: log backend word NOT changed
        if: steps.changed-word-backend.outputs.any_changed != 'true'
        run: echo backend word service NOT changed
  test-backend-word-changes:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: test word backend changes
    needs: [check-backend-word-changes]
    if: needs.check-backend-word-changes.outputs.changes_present == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: run word backend service unit tests
        working-directory: backend/service-word
        run: sbt coverage test
      - name: generate word backend service coverage report
        working-directory: backend/service-word
        run: sbt coverageReport
